version: "3.9"

services:
  db:
    image: postgres:15
    container_name: fastfood-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - fastfood_db_data:/var/lib/postgresql/data
    # Healthcheck para sabermos quando o Postgres está pronto
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s

  migrations:
    build: .
    container_name: fastfood-migrations
    # Espera até o Postgres estar "healthy"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: >
      sh -c "alembic upgrade head"
    volumes:
      - .:/app

  web:
    build: .
    container_name: fastfood-web
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      # Garantimos que o DB esteja saudável
      db:
        condition: service_healthy
    command: >
      sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    volumes:
      - .:/app
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

volumes:
  fastfood_db_data: