apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-food-app
  labels:
    app: fast-food
spec:
  replicas: 2  # Número inicial de réplicas
  selector:
    matchLabels:
      app: fast-food
  template:
    metadata:
      labels:
        app: fast-food
    spec:
      containers:
        - name: fastfood-web
          image: luanliduario/fast-food:latest
          ports:
            - containerPort: 8000
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
          envFrom:
            - configMapRef:
                name: fast-food-config
            - secretRef:
                name: fast-food-secrets
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
