apiVersion: v1
kind: Service
metadata:
  name: fast-food-service
spec:
  selector:
    app: fast-food
  ports:
    - protocol: TCP
      port: 80         # Porta que o serviço irá expor
      targetPort: 8000 # Porta do container (conforme definido no Deployment)
  type: ClusterIP      #  LoadBalancer se precisar expor externamente
