"""add order amount

Revision ID: 6e87cb238ed4
Revises: dc65c500236d
Create Date: 2025-01-20 00:55:19.419587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e87cb238ed4'
down_revision: Union[str, None] = 'dc65c500236d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'amount')
    # ### end Alembic commands ###
