"""order amount

Revision ID: 8aac6bec0aa3
Revises: 7a0c292a3d4d
Create Date: 2025-01-19 23:39:58.387050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aac6bec0aa3'
down_revision: Union[str, None] = '7a0c292a3d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'amount')
    # ### end Alembic commands ###
