"""client coupon overlaps

Revision ID: 93425d9bc8d8
Revises: ef14a87b3ce1
Create Date: 2025-01-21 00:06:44.601277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93425d9bc8d8'
down_revision: Union[str, None] = 'ef14a87b3ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
