"""add flag no cupom

Revision ID: a0d1417542ee
Revises: 7a0c292a3d4d
Create Date: 2025-01-19 20:09:51.647851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d1417542ee'
down_revision: Union[str, None] = '7a0c292a3d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('vip', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'vip')
    # ### end Alembic commands ###
