"""add descricao

Revision ID: dc65c500236d
Revises: a0d1417542ee
Create Date: 2025-01-19 20:48:44.863111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc65c500236d'
down_revision: Union[str, None] = 'a0d1417542ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('descricao', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'descricao')
    # ### end Alembic commands ###
