"""coupon overlaps

Revision ID: ef14a87b3ce1
Revises: 6e87cb238ed4
Create Date: 2025-01-21 00:04:04.760513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef14a87b3ce1'
down_revision: Union[str, None] = '6e87cb238ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
