"""fix_new_models_client_base_user_payment

Revision ID: f8a2dd21106a
Revises: 372d5e07e3cc
Create Date: 2025-01-18 16:58:22.695172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a2dd21106a'
down_revision: Union[str, None] = '372d5e07e3cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
